### ISSUE TITLE
No icon in the Configure Scene tab

### ISSUE THREAD

**Issue by yjeroen** [Javiondox/html-to-scene#4]
Minor issue, but you'd assume HTML to Scene has an icon as well:

![image](https://user-images.githubusercontent.com/1303988/152650063-ad9556d6-293f-40de-8b08-440e80e33c2a.png)

**Comment by Javiondox** [comment]
Seems like Foundry has updated Font Awesome and something broke, next build will have a similar icon to the one that was before.

**Comment by Javiondox** [comment]
Fixed on 1.2.0
